# -*- coding: utf-8 -*-
"""07_model_verification_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAf6SdQqWGne6caeXuP9NNxDNyHBG-R4

#**Importación de Librerías**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import os

# Procesamiento y Modelos
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

# Métricas
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, confusion_matrix, classification_report)

"""#**CONFIGURACIÓN DE ENTORNOS Y RUTAS**

En esta sección preparamos el espacio de trabajo local creando las carpetas necesarias para almacenar los entregables del proyecto de forma automatizada y ordenada.
"""

# Definimos la ruta raíz donde se guardará todo el trabajo
BASE = "./resultados_proyecto"
# os.makedirs crea las carpetas físicamente en el disco.
# 'exist_ok=True' evita que el código falle si las carpetas ya existen.
os.makedirs(f'{BASE}/metricas', exist_ok=True)
os.makedirs(f'{BASE}/modelos', exist_ok=True)

print("Entorno local configurado. Guardando resultados en:", BASE)

"""#**2. Carga, limpieza y preparación de datos**

Importamos el dataset preprocesado, corregimos los valores nulos (NaNs) para evitar errores en los algoritmos y separamos las características ($X$) de la variable objetivo ($y$).
"""

#cargar archivo csv
df = pd.read_csv('twitter_profiles_cleaned.csv')

# --- REPARACIÓN DE NaNs PARA EVITAR ERRORES ---
# Convertimos los True/False y NaNs a números (1 y 0) para que Scikit-Learn no reclame
df['is_real_location'] = df['is_real_location'].fillna(False).astype(int)
df['has_location'] = df['has_location'].fillna(0).astype(int)

# Definir características reales (X) y variable objetivo real (y = label)
features = ['followers_count', 'friends_count', 'post_count', 'has_location', 'is_real_location']
target = 'label'

X = df[features]
y = df[target]

# División estratificada (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Escalado de datos
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Datos listos. Registros de entrenamiento: {X_train_scaled.shape[0]}")

"""#**Entrenamiento y Comparación Base**

Entrenamos y evaluamos múltiples algoritmos de clasificación en paralelo con sus parámetros por defecto. Esto nos sirve para establecer una línea base y descubrir qué tipo de algoritmo se adapta mejor al problema.
"""

# Definimos un diccionario con los 4 algoritmos principales que vamos a comparar
models = {
    'Random Forest': RandomForestClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Logistic Regression': LogisticRegression(random_state=42)
}

metrics_list = []

print("Entrenando y evaluando modelos base (esto puede tardar unos segundos)...")

# Un bucle 'for' que entrena, predice y calcula las métricas básicas para cada modelo de forma automática
for name, model in models.items():
    model.fit(X_train_scaled, y_train) # El modelo "estudia" los datos de entrenamiento
    y_pred = model.predict(X_test_scaled) # El modelo intenta adivinar el set de prueba
# Guardamos los resultados (Accuracy, Precision, Recall y F1-Score) en una lista
    metrics_list.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, zero_division=0),
        'Recall': recall_score(y_test, y_pred, zero_division=0),
        'F1-Score': f1_score(y_test, y_pred, zero_division=0)
    })

# Convertimos la lista de resultados en un DataFrame, lo ordenamos por F1-Score y lo exportamos a CSV
df_metrics = pd.DataFrame(metrics_list).sort_values(by='F1-Score', ascending=False)
df_metrics.to_csv('resultado_modelos_base.csv', index=False)

print(" ¡Archivo 'resultado_modelos_base.csv' guardado {BASE}/metricas/!")
df_metrics.style.highlight_max(color='violet', axis=0)

"""#**Gráfico Comparativo de Métricas**"""

# Generamos un gráfico de barras para contrastar visualmente el rendimiento de los 4 modelos
# y lo guardamos como imagen de alta resolución (.png)

plt.figure(figsize=(10, 5))
df_melted = pd.melt(df_metrics, id_vars="Model", var_name="Metric", value_name="Value")
sns.barplot(x="Model", y="Value", hue="Metric", data=df_melted, palette="Pastel2")

plt.title("Comparación de Rendimiento de Modelos", fontsize=14, fontweight='bold')
plt.ylim(0.7, 1.02) # Nos enfocamos en la zona de rendimiento alto
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

# Guardar la imagen en la barra lateral
plt.savefig(f'{BASE}/metricas/grafico_comparativo.png', dpi=300)
plt.show()
print("¡Imagen 'grafico_comparativo.png' guardada con éxito!")

"""#**Optimización de Hiperparámetros (GridSearchCV)**

Tomamos el modelo ganador (Random Forest) y usamos búsqueda en grilla con validación cruzada (cv=3) para probar diferentes combinaciones de profundidad y cantidad de árboles, encontrando la estructura matemática óptima para el problema.
"""

print("Iniciando búsqueda de mejores parámetros con GridSearchCV...")
# Definimos el "menú" de opciones de configuración que queremos que pruebe el algoritmo
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],

}
# GridSearchCV se encarga de probar TODAS las combinaciones posibles usando validación cruzada
# Busca maximizar la métrica 'f1' (el balance perfecto entre precisión y recall)
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=3,
    scoring='f1',
    n_jobs=-1 # Usa todos los procesadores disponibles en Colab para acelerar el proceso
)

grid_search.fit(X_train_scaled, y_train)
best_rf = grid_search.best_estimator_ # Guardamos el modelo ganador absoluto

print("\n¡Optimización Completa!")
print(f"Mejores parámetros encontrados: {grid_search.best_params_}")

"""#**Reporte Final y Exportación del Modelo**

Evaluamos el modelo optimizado con datos completamente nuevos mediante un reporte de clasificación detallado y una matriz de confusión visual. Finalmente, exportamos el modelo listo para producción.
"""

# El modelo optimizado genera sus predicciones finales
y_pred_final = best_rf.predict(X_test_scaled)

print("Reporte de Clasificación Final:\n")
# 'classification_report' muestra la precisión clase por clase (cuántos humanos y cuántos bots acertó)
print(classification_report(y_test, y_pred_final))

# 'confusion_matrix' calcula los aciertos, falsos positivos y falsos negativos en una matriz
cm = confusion_matrix(y_test, y_pred_final)
# Diseñamos un mapa de calor (Heatmap) con Seaborn para que la matriz sea fácil de leer visualmente
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title("Matriz de Confusión Final", fontweight='bold')
plt.xlabel("Predicción del Modelo")
plt.ylabel("Clase Real")
plt.tight_layout()

# Guardar la matriz
plt.savefig(f'{BASE}/metricas/matriz_confusion_final.png', dpi=300)
plt.show()
print("¡Imagen 'matriz_confusion_final.png' guardada con éxito!")

"""#**Guardar el Modelo Entrenado**"""

# PERSISTENCIA DEL MODELO (Serialización):
# Con joblib.dump congelamos el modelo entrenado y calibrado en un archivo binario (.pkl).
# Esto permite que otra persona pueda usar el modelo en el futuro para predecir si una cuenta es bot sin necesidad de volver a entrenarlo desde cero.
ruta_modelo_final = f'{BASE}/modelos/modelo_twitter_final.pkl'
joblib.dump(best_rf, ruta_modelo_final)

print("-" * 60)
print(f" ¡PIPELINE EJECUTADO CON ÉXITO!")
print(f"Todo se guardó correctamente en la carpeta: '{BASE}'")
print(f"Modelo final listo para producción en: {ruta_modelo_final}")
print("-" * 60)

"""#**Gráficos Complementarios**

**GRÁFICO 1: CURVA ROC COMPARATIVA**
"""

print("\n--- Generando Gráficos Avanzados Corregidos ---")

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(10, 7))

# Curva para los modelos base
for name, model in models.items():
    if hasattr(model, "predict_proba"):
        y_probs = model.predict_proba(X_test_scaled)[:, 1]
        fpr, tpr, _ = roc_curve(y_test, y_probs)
        plt.plot(fpr, tpr, label=f'{name} (AUC = {auc(fpr, tpr):.4f})', lw=2)

# Curva para el modelo final optimizado con GridSearchCV
y_probs_opt = best_rf.predict_proba(X_test_scaled)[:, 1]
fpr_opt, tpr_opt, _ = roc_curve(y_test, y_probs_opt)
plt.plot(fpr_opt, tpr_opt, label=f'Random Forest Optimizado (AUC = {auc(fpr_opt, tpr_opt):.4f})',
         linestyle='--', color='black', lw=2.5)

plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Clasificador Aleatorio (AUC = 0.5000)')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Tasa de Falsos Positivos (1 - Especificidad)')
plt.ylabel('Tasa de Verdaderos Positivos (Sensibilidad)')
plt.title('Comparación de Curvas ROC Realistas (Sin Data Leakage)', fontsize=12, fontweight='bold')
plt.legend(loc="lower right")
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()

plt.savefig(f'{BASE}/metricas/curva_roc_corregida.png', dpi=300)
plt.show()
print(f" Nueva Curva ROC guardada en: {BASE}/metricas/curva_roc_corregida.png")

from google.colab import drive
drive.mount('/content/drive')

"""**GRÁFICO 2: IMPORTANCIA DE VARIABLES REALISTA**"""

importances = best_rf.feature_importances_
df_importance = pd.DataFrame({
    'Feature': features,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(9, 5))
sns.barplot(x='Importance', y='Feature', data=df_importance, palette='viridis')
plt.title('¿Qué características delatan REALMENTE a un Bot?', fontsize=12, fontweight='bold')
plt.xlabel('Importancia Relativa')
plt.ylabel('Variables de Cuenta')
plt.tight_layout()

plt.savefig(f'{BASE}/metricas/importancia_variables_real.png', dpi=300)
plt.show()
print(f"Nueva Importancia de Variables guardada en: {BASE}/metricas/importancia_variables_real.png")