# -*- coding: utf-8 -*-
"""02_supervised_modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16D9Iw6HKREQ8mVYTziqlABlGaEZNMEy4
"""

# Instalar Optuna y dependencias necesarias en caso de que la sesión no las tenga
!pip install -q optuna xgboost lightgbm

import pandas as pd
import numpy as np
import os
import warnings
import joblib

# Optuna para optimización bayesiana
import optuna

# Herramientas de Scikit-Learn
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

# Modelos y clasificadores
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING) # Evita saturar la consola con registros por cada intento
print("✅ Todas las librerías cargadas y listas")

# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')


# ============================================================================
# LOCALIZAR Y CARGAR EL CSV DESDE GOOGLE DRIVE
# ============================================================================
print("\n" + "="*60)
print("BUSCANDO ARCHIVO DATASET CSV EN DRIVE")
print("="*60)

csv_files = []
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.csv') and ('twitter' in file.lower() or 'profile' in file.lower()):
            filepath = os.path.join(root, file)
            size = os.path.getsize(filepath)
            csv_files.append((filepath, size))
            print(f"📄 Encontrado: {filepath} ({size:,} bytes)")

if csv_files:
    # Selecciona automáticamente el archivo procesado del pipeline
    filepath = csv_files[0][0]
    df = pd.read_csv(filepath)
    print(f"\n✅ Dataset cargado con éxito: {df.shape[0]} filas, {df.shape[1]} columnas")
    print(f"📊 Variables disponibles en el DataFrame:\n{df.columns.tolist()}")
else:
    print("❌ No se encontró el archivo automáticamente. Por favor, súbelo de forma manual:")
    from google.colab import files
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    df = pd.read_csv(filename)
    print(f"✅ Dataset cargado manualmente: {df.shape}")


# ============================================================================
# PREPARACIÓN DE DATOS (INGENIERÍA DE CARACTERÍSTICAS DE TWITTER)
# ============================================================================
# Definición estricta del vector de características final
feature_columns = ['followers_count', 'friends_count', 'post_count', 'has_location']
if 'is_real_location' in df.columns:
    feature_columns.append('is_real_location')

# Tratamiento e imputación inteligente y segura de valores nulos
for col in feature_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(0)

X = df[feature_columns].values
y = df['label'].values

# División estratificada de datos (80% Entrenamiento / 20% Prueba para Reserva)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\n✅ Datos estructurados correctamente.")
print(f"👉 Entrenamiento: {X_train.shape[0]} muestras | Prueba: {X_test.shape[0]} muestras.")


# ============================================================================
# AUDITORÍA DE CORRELACIÓN SENSITIVA (DETECCIÓN DE MULTICOLINEALIDAD)
# ============================================================================
print("\n🕵️‍♂️ Analizando coeficientes de correlación con la variable objetivo 'label'...")
correlaciones = df[feature_columns + ['label']].corr()['label'].sort_values(ascending=False)
print(correlaciones)


# ============================================================================
# CONFIGURACIÓN DE LA FUNCIÓN OBJETIVO DE OPTUNA (ALINEADO AL MANDATO DOCENTE)
# ============================================================================
def objective(trial, X, y):
    steps = []

    # 1. PASO OBLIGATORIO: Escalamiento estándar para balancear las magnitudes de Twitter
    steps.append(('scaler', StandardScaler()))

    # 2. PCA CONDICIONAL: Optuna determina si la reducción espacial remueve ruido del dataset
    use_pca = trial.suggest_categorical("use_pca", [True, False])
    if use_pca:
        pca_variance = trial.suggest_categorical("pca_variance", [0.85, 0.90, 0.95])
        steps.append(('pca', PCA(n_components=pca_variance, random_state=42)))

    # 3. SELECCIÓN DEL MODELO: Fijamos unívocamente LightGBM como el clasificador del proyecto.
    # Optuna dirigirá el 100% de sus iteraciones a tunear este algoritmo de alta velocidad.
    classifier_name = "LightGBM"

    # Espacio latente de búsqueda de hiperparámetros para el modelo campeón elegido
    lgb_n_estimators = trial.suggest_int("lgb_n_estimators", 50, 150)
    lgb_lr = trial.suggest_float("lgb_learning_rate", 0.01, 0.2, log=True)

    model = LGBMClassifier(
        n_estimators=lgb_n_estimators,
        learning_rate=lgb_lr,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1,
        verbose=-1
    )

    # Acoplar los hiperparámetros y estructurar el Pipeline secuencial
    steps.append(('classifier', model))
    pipeline = Pipeline(steps)

    # 4. VALIDACIÓN CRUZADA ESTRATIFICADA: Evaluación robusta para mitigar el azar
    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

    # Optimizamos enfocados en F1-Score para proteger al negocio contra desbalances de clases
    score = cross_val_score(pipeline, X_train, y_train, cv=cv, scoring='f1', n_jobs=-1)

    return score.mean()


# ============================================================================
# OPTIMIZACIÓN BAYESIANA GLOBAL
# ============================================================================
print("\n🚀 Iniciando búsqueda del Pipeline óptimo e hiperparámetros con Optuna...")

study = optuna.create_study(direction="maximize")
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=30)

print("\n" + "="*60)
print(f"👑 PIPELINE GANADOR SELECCIONADO POR OPTUNA:")
print(f"📊 Mejor F1-Score obtenido (Validación Cruzada): {study.best_value:.4f}")
print(f"⚙️ Hiperparámetros y pasos óptimos: {study.best_params}")
print("="*60 + "\n")

# Guardar localmente y preparar rutas para Drive
os.makedirs("outputs/models", exist_ok=True)
joblib.dump(study.best_params, "outputs/models/best_params.pkl")


# ============================================================================
# EVALUACIÓN FINAL DE PRODUCCIÓN (DATOS DE RESERVA NO VISTOS)
# ============================================================================
print("🔄 Reconstruyendo el pipeline óptimo para auditoría de producción...")

BASE_PATH = '/content/drive/MyDrive/twitter_project'
os.makedirs(f"{BASE_PATH}/outputs/models", exist_ok=True)
os.makedirs(f"{BASE_PATH}/data/processed", exist_ok=True)

best_params = study.best_params
final_steps = [('scaler', StandardScaler())]

# 1. Reconstruir PCA si la optimización probabilística dictaminó que aportaba valor
if best_params["use_pca"]:
    final_steps.append(('pca', PCA(n_components=best_params["pca_variance"], random_state=42)))

# 2. Inicializar LightGBM con la combinación de parámetros ganadora de Optuna
final_model = LGBMClassifier(
    n_estimators=best_params["lgb_n_estimators"],
    learning_rate=best_params["lgb_learning_rate"],
    class_weight='balanced',
    random_state=42,
    n_jobs=-1,
    verbose=-1
)

final_steps.append(('classifier', final_model))
best_pipeline = Pipeline(final_steps)

# 3. Ajuste definitivo sobre el conjunto de entrenamiento limpio
best_pipeline.fit(X_train, y_train)

# 4. Inferencia y predicción sobre los datos de validación retenidos
y_pred_test = best_pipeline.predict(X_test)

# 5. Despliegue de métricas en consola
print("\n📊 REPORTE DE CLASIFICACIÓN DE PRODUCCIÓN DE LIGHTGBM (Datos de Prueba):")
print("-" * 75)
print(classification_report(y_test, y_pred_test, target_names=['Real Account', 'Bot']))


# ============================================================================
# PERSISTENCIA DE ARTEFACTOS ANALÍTICOS EN GOOGLE DRIVE (MLOps)
# ============================================================================
print("\n" + "="*60)
print("💾 EXPORTANDO Y GUARDANDO ARTEFACTOS EN GOOGLE DRIVE...")
print("="*60)

# Guardar los metadatos de configuración
joblib.dump(best_params, f"{BASE_PATH}/outputs/models/best_params.pkl")
print("✅ Diccionario de hiperparámetros guardado en: outputs/models/best_params.pkl")

# Guardar el binario entrenado (el "cerebro" del pipeline)
joblib.dump(best_pipeline, f"{BASE_PATH}/outputs/models/best_pipeline_model.pkl")
print("✅ Objeto Pipeline serializado y exportado a: outputs/models/best_pipeline_model.pkl")

# Exportar conjuntos de datos en formato CSV para garantizar reproducibilidad
pd.DataFrame(X_test).to_csv(f"{BASE_PATH}/data/processed/X_test.csv", index=False)
pd.DataFrame(y_test).to_csv(f"{BASE_PATH}/data/processed/y_test.csv", index=False)

print("✅ Conjunto X_test.csv exportado con éxito a: data/processed/")
print("✅ Conjunto y_test.csv exportado con éxito a: data/processed/")
print("\n🎉 ¡Pipeline de optimización finalizado y estabilizado bajo la arquitectura de LightGBM!")